
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 17 23:46:00 CST 2022
//----------------------------------------------------

package ejerciciojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Char = 16;
  public static final int EstruControl = 12;
  public static final int ExprLogica = 5;
  public static final int Entero = 13;
  public static final int ERROR = 17;
  public static final int Flotante = 4;
  public static final int Tipo = 2;
  public static final int Separador = 8;
  public static final int Operador = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Id = 15;
  public static final int Nulo = 3;
  public static final int ExprFinal = 9;
  public static final int Comparador = 10;
  public static final int Asig = 7;
  public static final int String = 11;
  public static final int Boolean = 6;
}

