
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 18 02:22:54 CST 2022
//----------------------------------------------------

package ejerciciojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Asig = 7;
  public static final int Entero = 13;
  public static final int Coma = 39;
  public static final int Nulo = 3;
  public static final int If = 19;
  public static final int Id = 15;
  public static final int ExprLogica = 5;
  public static final int LlaveC = 35;
  public static final int LlaveA = 36;
  public static final int Default = 27;
  public static final int Operador = 14;
  public static final int Separador = 8;
  public static final int Else = 20;
  public static final int Break = 25;
  public static final int ExprFinal = 9;
  public static final int Return = 24;
  public static final int While = 21;
  public static final int Division = 32;
  public static final int Int = 17;
  public static final int Flotante = 4;
  public static final int Cadena = 11;
  public static final int For = 22;
  public static final int EOF = 0;
  public static final int DosPuntos = 40;
  public static final int CorcheteC = 38;
  public static final int error = 1;
  public static final int CorcheteA = 37;
  public static final int Switch = 23;
  public static final int Tipo = 2;
  public static final int Char = 16;
  public static final int EstruControl = 12;
  public static final int Print = 28;
  public static final int ERROR = 41;
  public static final int Case = 26;
  public static final int Comparador = 10;
  public static final int String = 18;
  public static final int Resta = 31;
  public static final int ParentesisC = 33;
  public static final int Boolean = 6;
  public static final int Multiplicacion = 29;
  public static final int ParentesisA = 34;
  public static final int Suma = 30;
}

